### ISSUE TITLE
SSLException

### ISSUE THREAD

**Issue by calves07** [redouane59/twittered#248]
I have faced this error multiple times when making requests, normally if I try again, it works... any thoughts?

````
javax.net.ssl.SSLException: Connection reset
	at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:352) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:295) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:290) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1521) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:965) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:290) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
	at sun.net.www.MeteredStream.read(MeteredStream.java:134) ~[?:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:181) ~[?:?]
	at com.github.scribejava.core.utils.StreamUtils.getStreamContents(StreamUtils.java:28) ~[scribejava-core-8.1.0.jar:?]
	at com.github.scribejava.core.model.Response.parseBodyContents(Response.java:51) ~[scribejava-core-8.1.0.jar:?]
	at com.github.scribejava.core.model.Response.getBody(Response.java:67) ~[scribejava-core-8.1.0.jar:?]
	at io.github.redouane59.twitter.helpers.AbstractRequestHelper.makeRequest(AbstractRequestHelper.java:91) ~[twittered-3.2.jar:?]
	at io.github.redouane59.twitter.helpers.AbstractRequestHelper.makeRequest(AbstractRequestHelper.java:81) ~[twittered-3.2.jar:?]
	at io.github.redouane59.twitter.helpers.AbstractRequestHelper.makeRequest(AbstractRequestHelper.java:59) ~[twittered-3.2.jar:?]
	at io.github.redouane59.twitter.helpers.RequestHelper.getRequestWithParameters(RequestHelper.java:60) ~[twittered-3.2.jar:?]
	at io.github.redouane59.twitter.helpers.RequestHelper.getRequest(RequestHelper.java:55) ~[twittered-3.2.jar:?]
	at io.github.redouane59.twitter.TwitterClient.getUserIdsByRelation(TwitterClient.java:208) ~[twittered-3.2.jar:?]
	at io.github.redouane59.twitter.TwitterClient.getFollowersIds(TwitterClient.java:283) ~[twittered-3.2.jar:?]
	at twitter.API.getRelatedUsersUsingLists(API.java:147) [classes/:?]
	at twitter.ConnectionsController.getFollowersV2(ConnectionsController.java:28) [classes/:?]
	at twitter.Main.main(Main.java:26) [classes/:?]
	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
		at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110) ~[?:?]
		at java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[?:?]
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:83) ~[?:?]
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:383) ~[?:?]
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:295) ~[?:?]
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:290) ~[?:?]
		at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1521) ~[?:?]
		at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:965) ~[?:?]
		at java.io.BufferedInputStream.read1(BufferedInputStream.java:290) ~[?:?]
		at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
		at sun.net.www.MeteredStream.read(MeteredStream.java:134) ~[?:?]
		at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:?]
		at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510) ~[?:?]
		at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:?]
		at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
		at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
		at java.io.InputStreamReader.read(InputStreamReader.java:181) ~[?:?]
		at com.github.scribejava.core.utils.StreamUtils.getStreamContents(StreamUtils.java:28) ~[scribejava-core-8.1.0.jar:?]
		at com.github.scribejava.core.model.Response.parseBodyContents(Response.java:51) ~[scribejava-core-8.1.0.jar:?]
		at com.github.scribejava.core.model.Response.getBody(Response.java:67) ~[scribejava-core-8.1.0.jar:?]
		at io.github.redouane59.twitter.helpers.AbstractRequestHelper.makeRequest(AbstractRequestHelper.java:91) ~[twittered-3.2.jar:?]
		at io.github.redouane59.twitter.helpers.AbstractRequestHelper.makeRequest(AbstractRequestHelper.java:81) ~[twittered-3.2.jar:?]
		at io.github.redouane59.twitter.helpers.AbstractRequestHelper.makeRequest(AbstractRequestHelper.java:59) ~[twittered-3.2.jar:?]
		at io.github.redouane59.twitter.helpers.RequestHelper.getRequestWithParameters(RequestHelper.java:60) ~[twittered-3.2.jar:?]
		at io.github.redouane59.twitter.helpers.RequestHelper.getRequest(RequestHelper.java:55) ~[twittered-3.2.jar:?]
		at io.github.redouane59.twitter.TwitterClient.getUserIdsByRelation(TwitterClient.java:208) ~[twittered-3.2.jar:?]
		at io.github.redouane59.twitter.TwitterClient.getFollowersIds(TwitterClient.java:283) ~[twittered-3.2.jar:?]
		at twitter.API.getRelatedUsersUsingLists(API.java:147) [classes/:?]
		at twitter.ConnectionsController.getFollowersV2(ConnectionsController.java:28) [classes/:?]
		at twitter.Main.main(Main.java:26) [classes/:?]
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:186) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1308) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:949) ~[?:?]
	... 22 more
````

**Comment by redouane59** [comment]
Hmmmm I never had it on my side, don't have any idea :/
