### ISSUE TITLE
TwitterClient startFilteredStream stop receiving tweet

### ISSUE THREAD

**Issue by akuma0** [redouane59/twittered#439]
Hi !
I don't understand why but after few minutes or few hours, onTweetStreamed stop received data, no error anywhere.
onStreamError, onUnknownDataStreamed or onStreamEnded didn't be call either...
Twitter monthly tweet cap usage at 3%

Any idea ?
(Running on v1.26)

Edit : 2023/03/22 :
It's looks relate to : 
 - redouane59/twittered/issues/435
 - redouane59/twittered/discussions/362

**Comment by akuma0** [comment]
UPDATE :
I've upgrade to v2.21 yesterday and today after 754 minutes of use i've got this error in onStreamEnded :

`java.io.IOException: Premature EOF
	at java.base/sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:568)
	at java.base/sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:612)
	at java.base/sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:699)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at io.github.redouane59.twitter.helpers.TweetStreamConsumer.readSocket(TweetStreamConsumer.java:81)
	at io.github.redouane59.twitter.helpers.TweetStreamConsumer.lambda$consumeStream$0(TweetStreamConsumer.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by akuma0** [comment]
Resolved by checked tweets reception every minute.
